apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-jegan # Replace 'jegan' with your name
  labels:
    name: jegan # Replace 'jegan' with your name
    app: mariadb
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.15.35 # Replace this IP with your respective 
    path: /var/nfs/jegan/share2 # Replace this with your nfs path /var/nfs/user[xy]/share2

