apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-jegan # Replace 'jegan' with your name
spec:
  storageClassName: manual
  selector:
    matchLabels:
      name: jegan  # Replace 'jegan' with your name
      app: wordpress  
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
