apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc-{{.Values.pv_label}}
spec:
  storageClassName: manual
  selector:
    matchLabels:
      name: {{.Values.pv_label}}
      app: mariadb
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{.Values.nfs.mariadb_pv_size}}
