apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-jegan # Replace 'jegan' with your name
  labels:
    name: jegan # Replace 'jegan' with your name
    app: wordpress
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  peristentVolumeReclaimPolicy: Delete
  nfs:
    server: 10.10.15.35 # Replace with your linux server IP
    path: /var/nfs/jegan/share1 # Replace 'jegan' with your linux username user[xy]
