apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-{{.Values.pv_label}}
  labels:
    name: {{.Values.pv_label}}
    app: wordpress
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.nfs.wordpress_pv_size}} 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  peristentVolumeReclaimPolicy: Delete
  nfs:
    server: {{.Values.nfs.ip}} 
    path: {{.Values.nfs.wordpress_pv_path}} 
